# Use a lightweight base image
FROM maven:3

# Install required packages
RUN apk add --no-cache openjdk17-jre maven 

# Set the working directory
WORKDIR /app

# Copy the pom.xml file
COPY pom.xml ./

# Command to run Maven
CMD ["mvn", "clean", "package"]
